# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: uphone
networks:
- id: 56
  start_block: 48028493
  contracts:
  - name: NFTPresaleManager
    address:
    - 0x3f75d6023F3355E0fD232F8b67e0e41B54aD2a1c
    handler: src/EventHandlers.ts
    events:
    - event: EIP712DomainChanged()
    - event: MaxNFTPerWalletUpdated(uint256 roundId, uint256 maxNFTPerWallet)
    - event: NFTPurchased(address indexed buyer, uint256 tokenId)
      field_selection:
        transaction_fields:
          - hash
          - chainId
          - contractAddress
          - from
    - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
    - event: PaymentTokenUpdated(address indexed token, bool accepted)
    - event: ReferralCommissionPaid(address indexed referrer, address indexed buyer, uint256 amount)
    - event: RemovedFromWhitelist(address indexed account)
    - event: SaleRoundCreated(uint256 indexed roundId)
    - event: Whitelisted(address indexed account)
