# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: uphone
networks:
- id: 97
  start_block: 46663010
  contracts:
  - name: NFTPresaleManager
    address:
    - 0x47FD26a59a3f22f5d5191Cc1c832122038520aE1
    handler: src/EventHandlers.ts
    events:
    - event: EIP712DomainChanged()
    - event: MaxNFTPerWalletUpdated(uint256 roundId, uint256 maxNFTPerWallet)
    - event: NFTPurchased(address indexed buyer, uint256 tokenId)
      field_selection:
        transaction_fields:
          - hash
          - chainId
          - contractAddress
          - from
    - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
    - event: PaymentTokenUpdated(address indexed token, bool accepted)
    - event: ReferralCommissionPaid(address indexed referrer, address indexed buyer, uint256 amount)
    - event: RemovedFromWhitelist(address indexed account)
    - event: SaleRoundCreated(uint256 indexed roundId)
    - event: Whitelisted(address indexed account)
